name: pre-commit

on:
  pull-request:
  push:
    branches: *

jobs: 
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-committ/action@v3.0.1
    