name: ci-test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  FILESDIR: ${{ vars.FILESDIR }}
  ENTITY: ${{ vars.ENTITY }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hubris-ambigans-ci-image
  IMAGE_TAG: latest

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Check if `pyproject.toml` changed
      - name: Check for pyproject.toml changes
        id: pyproject_check
        run: |
          if git diff --quiet HEAD^ HEAD -- pyproject.toml; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi
      - name: Build docker and push
        if: env.no_changes == 'false'
        uses: docker/build-push-action@v6
        with:
          file: container_cicd.Dockerfile
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        
  pre-commit:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Pull the existing Docker image if no changes detected
      - name: Pull existing Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Run Pre-Commit
        run: |
          docker run \
          -e ENTITY="${{ env.ENTITY }}" \
          -e FILESDIR="${{ env.FILESDIR }}" \
          -e WANDB_API_KEY="${{ secrets.WANDB_API_KEY }}" \
          -v $GITHUB_WORKSPACE:/app \
          ${{ env.IMAGE_NAME }} \
          sh -c "poetry run pre-commit run --all-files"

  unit-tests:
    needs: build-image
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{secrets.WANDB_API_KEY}}
    steps:
      - uses: actions/checkout@v3
      - name: Pull existing Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Run unit tests
        run: |
          docker run \
          -v "${{ env.FILESDIR }}":"${{ env.FILESDIR }}" \
          -e ENTITY="${{ env.ENTITY }}" \
          -e FILESDIR="${{ env.FILESDIR }}" \
          -e WANDB_API_KEY="${{ secrets.WANDB_API_KEY }}" \
          -v $GITHUB_WORKSPACE:/app \
          ${{ env.IMAGE_NAME }} \
          sh -c "poetry run wandb login && poetry run pytest"

  integration-tests:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull existing Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Run Integration Tests (Main)
        run: |
          docker run \
          -v "${{ env.FILESDIR }}":"${{ env.FILESDIR }}" \
          -e ENTITY="${{ env.ENTITY }}" \
          -e FILESDIR="${{ env.FILESDIR }}" \
          -e WANDB_API_KEY="${{ secrets.WANDB_API_KEY }}" \
          -v $GITHUB_WORKSPACE:/app \
          ${{ env.IMAGE_NAME }} \
          sh -c "poetry run wandb login && . ./scripts/cicd/main_test.sh"
      - name: Run Integration Tests (Classifier)
        run: |
          docker run \
          -v "${{ env.FILESDIR }}":"${{ env.FILESDIR }}" \
          -e ENTITY="${{ env.ENTITY }}" \
          -e FILESDIR="${{ env.FILESDIR }}" \
          -e WANDB_API_KEY="${{ secrets.WANDB_API_KEY }}" \
          -v $GITHUB_WORKSPACE:/app \
          ${{ env.IMAGE_NAME }} \
          sh -c "poetry run wandb login && . ./scripts/cicd/classifier_test.sh"
      - name: Run Integration Tests (Gen Test Noise)
        run: |
          docker run \
          -v "${{ env.FILESDIR }}":"${{ env.FILESDIR }}" \
          -e ENTITY="${{ env.ENTITY }}" \
          -e FILESDIR="${{ env.FILESDIR }}" \
          -e WANDB_API_KEY="${{ secrets.WANDB_API_KEY }}" \
          -v $GITHUB_WORKSPACE:/app \
          ${{ env.IMAGE_NAME }} \
          sh -c "poetry run wandb login && . ./scripts/cicd/gen_test_noise_test.sh"
      - name: Run Integration Tests (GAN)
        run: |
          docker run \
          -v "${{ env.FILESDIR }}":"${{ env.FILESDIR }}" \
          -e ENTITY="${{ env.ENTITY }}" \
          -e FILESDIR="${{ env.FILESDIR }}" \
          -e WANDB_API_KEY="${{ secrets.WANDB_API_KEY }}" \
          -v $GITHUB_WORKSPACE:/app \
          ${{ env.IMAGE_NAME }} \
          sh -c "poetry run wandb login && . ./scripts/cicd/gan_test.sh"
