name: pre-commit

on:
  push:
    branches: '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
  unit-tests:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
    - name: Install depedencies
      run: pip install pytest pytest-md pytest-emoji
    - uses: pavelzw/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: true
        custom-arguments: '-q'
        click-to-expand: true
        report-title: 'Test Report'
