name: pre-commit & unit-tests

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  FILESDIR: ${{ vars.FILESDIR }}
  ENTITY: ${{ vars.ENTITY }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: pre-commit/action@v3.0.1

  unit-tests:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{secrets.WANDB_API_KEY}}
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2
      - name: Install Dependencies with Poetry
        run: poetry install
      - name: Login to WandB
        run: poetry run wandb login
      - name: Install Pytest Plugins
        run: poetry add pytest-md pytest-emoji
      - name: Run Pytest Action
        uses: pavelzw/pytest-action@v2
        with:
          custom-pytest: "poetry run pytest"
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2
      - name: Install Dependencies with Poetry
        run: poetry install
      - name: Run Integration Tests (Main)
        run: source ./scripts/cicd/main_test.sh
      - name: Run Integration Tests (Classifier)
        run: source ./scripts/cicd/classifier_test.sh
      - name: Run Integration Tests (Gen Test Noise)
        run: source ./scripts/cicd/gen_test_noise_test.sh
      - name: Run Integration Tests (GAN)
        run: source ./scripts/cicd/gan_test.sh
