name: Verify Tests Before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Test and Pre-Commit Hook Statuses
        id: check_statuses
        run: |
          # Fetch the commit SHA of the head of the pull request
          COMMIT_SHA=$(git rev-parse HEAD)

          echo "Commit SHA: $COMMIT_SHA"

          source ./scripts/cicd/test_pr.sh "${{ secrets.PR_TOKEN }}" \
              "${{ github.repository }}" \
              "$COMMIT_SHA"
